- hosts: remoto
  gather_facts: False
  tasks:

  - name:
    shell: "date -u"
    register: linux_date

  - name: debug
    debug:
      msg: "{{ linux_date }}"

  - name: condicional
    shell: "echo OLA > /tmp/arquivo"
    when: linux_date.failed == false